# Generated by Django 4.0.5 on 2022-06-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_user_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='starting_bid',
            new_name='bid',
        ),
    ]
