# Generated by Django 4.0.5 on 2022-06-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_starting_bid_listings_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listing_owner',
            field=models.ManyToManyField(blank=True, related_name='owner', to='auctions.listings'),
        ),
    ]
