# Generated by Django 4.0.5 on 2022-07-04 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listings_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='comments',
        ),
        migrations.CreateModel(
            name='Coments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.listings')),
                ('owner', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
