# Generated by Django 4.0.5 on 2022-07-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_comments_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='owner',
        ),
        migrations.AddField(
            model_name='comments',
            name='owner',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
