# Generated by Django 4.0.5 on 2022-07-04 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_comments_listing_alter_comments_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='listing',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.listings'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='owner',
            field=models.CharField(max_length=64),
        ),
    ]
