# Generated by Django 4.0.5 on 2022-07-04 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_comments_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('listings', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='auctions.listings')),
            ],
        ),
    ]
