# Generated by Django 4.0.5 on 2022-07-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_categories_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='listings',
        ),
        migrations.AddField(
            model_name='categories',
            name='listings',
            field=models.ManyToManyField(blank=True, null=True, related_name='category', to='auctions.listings'),
        ),
    ]
